### ISSUE TITLE
Missing fip.bin info?

### ISSUE THREAD

**Issue by vchong** [Linaro/documentation#26]
Hi,

Why does https://github.com/Linaro/documentation/blob/master/Reference-Platform/Releases/RPB_16.06/ConsumerEdition/HiKey/InstallDebianRPB.md not contain instructions to download and flash fip.bin? If fip.bin is not updated together with the other images, some of OP-TEE components might get mismatched in versions.

Thanks!

**Comment by fixxxxxxer** [comment]
@vchong 

My understanding is that you only need fip.bin for board recovery when flashing the bootloader.

https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/BoardRecovery.md

If you are simply reflashing user space, boot and rootfs, you do not need fip.bin.

Please correct me if I am wrong.

**Comment by vchong** [comment]
@sdrobertw,

There are correlations between OP-TEE components in both the bootloader and kernel and rootfs so say if a user is say upgrading from 16.03 to 16.06 without updating fip.bin as well, then some stuffs may break. Besides, it's not a lot of extra work to download and flash fip.bin so probably better and safer to just include it. Less problem and maintenance for us as well down the road.

Thanks!

**Comment by fixxxxxxer** [comment]
@vchong, I saw you submitted a pull request, was that to fix this issue?

**Comment by vchong** [comment]
@sdrobertw Yes. Will close this. Thanks!
