### ISSUE TITLE
DragonBoard in HiKey install instructions

### ISSUE THREAD

**Issue by Jeeppler** [Linaro/documentation#3]
The following sentence in the debian hikey install instructions is confusing:

> The SD card method allows you to place a microSD card into the DragonBoard™ 410c to automatically boot

https://github.com/Linaro/documentation/blob/master/Reference-Platform/RPOfficial/ConsumerEdition/HiKey/InstallDebianRPB.md

The install instructions are for the HiKey reference platform. DragonBoard™ 410c should be replaced with HiKey or HiKey and LeMaker HiKey, because it is for both models.

**Comment by fixxxxxxer** [comment]
This change has been made. Thank you!

Please see commit:
https://github.com/Linaro/documentation/commit/069ec49f5bef38059f9f8917d372c5da5b79d7fd
