### ISSUE TITLE
Wrong description of the ptable file.

### ISSUE THREAD

**Issue by Tony-HIT** [Linaro/documentation#30]
In the documents, it shows:
All HiKey CircuitCo boards will use the 4G files
All HiKey LeMaker 1G boards will use the 4G files
All HiKey LeMaker 2G boards will use the 8G files

But the correct should be:
All HiKey CircuitCo boards will use the 4G files
All HiKey LeMaker 1G boards will use the 8G files
All HiKey LeMaker 2G boards will use the 8G files

Becasue both HiKey LeMaker 1GB or 2GB use 8GB emmc flash on the board

**Comment by vchong** [comment]
See https://github.com/Linaro/documentation/pull/31
