### ISSUE TITLE
HiKey install instructions flash system does not work

### ISSUE THREAD

**Issue by Jeeppler** [Linaro/documentation#4]
The following instruction is not correct: 

> $ sudo fastboot flash system hikey-jessie_alip_YYYYMMDD-nnn-Xg.emmc.img

the filename pattern is wrong for build 16.06.

the correct command should be:

`sudo fastboot flash system hikey-rootfs-debian-jessie-alip-YYYYMMDD-nnn.emmc.img`

for example:

`sudo fastboot flash system hikey-rootfs-debian-jessie-alip-20160629-120.emmc.img`

**Comment by fixxxxxxer** [comment]
This has been fixed, thank you!

Please see commit:
https://github.com/Linaro/documentation/commit/a8f1e1982d5be7135e33ee9d58cb462db0c7d4ea
