### ISSUE TITLE
adding the dtb file to /boot in rootfs for u-boot support

### ISSUE THREAD

**Issue by kamomil** [Linaro/documentation#52]
Hi,
I try to add u-boot support to build the dragonboard-410c, for that, the dtb file should be added to `/boot` on the rootfs image. On the `run.do_install` file I see that `do_install` of `linux-linaro-qcomlt`, does add it to ${D}:

```
install -m 0644 ${DTB_PATH} /home/dafna/oe-rpb/build-rpb/tmp-rpb-glibc/work/dragonboard_410c-linaro-linux/linux-linaro-qcomlt/4.9-r0/image/boot/devicetree-${DTB_SYMLINK_NAME}.${DTB_EXT}
```

but it is not in the final image, can I get a direction of how to add it ? 
Thank you

**Comment by Mani-Sadhasivam** [comment]
@kamomil Could you please take your question to [96Boards Forum](https://discuss.96boards.org/c/products/dragonboard410c)? All the technical discussions around 96Boards happens only in forum under relevant board section.

**Comment by kamomil** [comment]
ok, sorry
